sudo: required

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.19.0
    - DOCKER_IMAGE=water-spring-config-server

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 > clair-scanner
  - chmod +x clair-scanner
  - sudo mv docker-compose /usr/local/bin
  - sudo mv clair-scanner /usr/local/bin
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - git clone https://github.com/docker/docker-bench-security.git

install:
  - cd .travis
  - docker-compose -f docker-compose up -d --build
  - cd ..

script:
  - cd docker-bench-security
  - sudo sh docker-bench-security.sh -c container_images
  - docker ps | grep -q water-auth-server
  - for run in {1..20};do sleep 1;if docker logs $DOCKER_IMAGE 2>&1 | grep -q "Started Application"; then echo "Application is running";break;else echo "Still checking for application startup. Check ${run} of 20";fi;done
  - curl -s -k -f https://127.0.0.1:8888/actuator/health --silent 2>&1 | grep -q '{"status":"UP"}'
  - docker run -d --name db arminc/clair-db
  - docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.3
  - clair-scanner -c "http://127.0.0.1:6060" --ip "$(ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')" $DOCKER_IMAGE:latest
