---
  version: '3.5'

  services:
    server:
      container_name: water-spring-config-server
      build:
        context: ../
      image: water-spring-config-server
      ports:
        - "8888:8888"
      volumes:
        - ./configs:/configs/
        - ./secrets:/secrets/
        - ./certs:/certs/:ro
        - ./configuration:/configuration/:ro
      env_file:
        - docker-compose.env
